export * from './academic-history.proxy.service';
export * from './campus.proxy.service';
export * from './costs.proxy.service';
export * from './oauth2.proxy.service';
export * from './payments.proxy.service';
export * from './report-card.proxy.service';
export * from './sf-core.proxy.service';
export * from './sf-picklist.proxy.service';
export * from './sf-servicios-escolares.proxy.service';
