# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy AzureWebApp - app-cv-sschc-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://lottus.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b34727d3d88d4638b4096ed4632240d4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_70ffe00c88774dfa83833ef529bc6d98 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: lottus.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b34727d3d88d4638b4096ed4632240d4 }}/cv-sschc:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-cv-sschc-prod'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_024a99fb3dd84df7863f3261b2f85fc7 }}
        images: 'lottus.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b34727d3d88d4638b4096ed4632240d4 }}/cv-sschc:${{ github.sha }}'
