# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Stage AzureWebApp - app-cv-sschc-qa

on:
  push:
    branches:
      - stage
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        # This action needs access to the history and tags.
        # With 'fetch-depth: 0' the action fetches the complete history and all tags.
        # You can also limit the depth to a certain number and run
        # with 'fetch-tags: true'. The produced version number might not
        # be accurate in that case.
        fetch-depth: 0
    
    - name: Run Git Version
      id: gitversion
      uses: toitlang/action-git-version@v1.1.0

    - name: Use the version
      shell: bash
      run: |
        echo ${{ steps.gitversion.outputs.version }}

    - name: Get short Gitversion
      id: get-short-gitver
      run: |
        short=$(echo ${{steps.gitversion.outputs.version}} | cut -c 1-7)
        short+=$(echo stage-)
        short+=$(echo ${{steps.gitversion.outputs.version}} | cut -c 23-)
        echo "::set-output name=short::$short"
        echo ${{ steps.get-short-gitver.outputs.short }}
        echo $GITVERSION
        
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://lottus.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_8e84e78b549d4cd6b82031898ceadcff }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4e92aee308b640169b83bfa34928f848 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: lottus.azurecr.io/cv-sschc:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'stage'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-cv-sschc-qa'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_645d8643fe0a450ea25b2dac7125a5ec }}
        images: 'lottus.azurecr.io/cv-sschc:${{ github.sha }}'
