# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - app-cv-sschc-qa

on:
  push:
    branches:
      - stage
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://lottus.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_8e84e78b549d4cd6b82031898ceadcff }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4e92aee308b640169b83bfa34928f848 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: lottus.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8e84e78b549d4cd6b82031898ceadcff }}/cv-sschc:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-cv-sschc-qa'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_645d8643fe0a450ea25b2dac7125a5ec }}
        images: 'lottus.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8e84e78b549d4cd6b82031898ceadcff }}/cv-sschc:${{ github.sha }}'